### PR TITLE
enhance: add entities table

### PR DESCRIPTION
**Pull request by marcelgerber**
Think this should be uncontroversial.

### CODE REVIEW

**Review by danyx23 — APPROVED** [review]
Sure - we don't have data_values in datasette so I thought entities doesn't give us much. Did you have a reason for including it?

**Comment by marcelgerber** [comment]
Yeah, so we can check for alternative spellings of the same entity, for example.
But yeah, there's not a lot of join-ability right now.

**Comment by Marigold** [comment]
By the way `data_values` for ETL datasets don't exist anymore, so not sure about the value of adding it there. (We could find a way how to add `data_values` to BigQuery if we really wanted them. Or just iterate over all datasets from our catalog with python script.)

**Comment by marcelgerber** [comment]
Yeah, I think the main reason why we don't want to include `data_values` is just its sheer size, which would bog down Datasette quite a bit.

**Pull request merged**
